### PR TITLE
Add CO2, eCO2 sensor types

### PR DESCRIPTION
**Pull request by brentru**
Resolves https://github.com/adafruit/Adafruit_Sensor/issues/44

### CODE REVIEW

**Comment by caternuson** [comment]
Can leave `library.properties` unchanged. Whoever comes along to make the next release can deal with that.

Totally cosmetic - should it be all caps?
```
SENSOR_TYPE_ECO2
```

**Comment by caternuson** [comment]
oops. nvm. been merged.

**Comment by brentru** [comment]
@caternuson  Will address in branch i'm checking out,

> Totally cosmetic - should it be all caps?

Yeah I believe so, will update this here: https://github.com/adafruit/Adafruit_Sensor/pull/46

I'm going to cut a release shortly so I'd like .properties updated. For next time - are we leaving .properties alone for non-urgent releases?

**Comment by caternuson** [comment]
In general, yah, I think leave `library.properties` alone in the actual PR. Sometimes a release may be multiple PRs merged in no particular order. Or other reasons that may warrant a different sem ver number. And it's trivial to edit `library.properties` right before an actual release (i just use github's web edit).

**Pull request merged**
